/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hobbitus Ryzen
 */
public class InsertCar extends javax.swing.JFrame {

    /**
     * Creates new form InsertCar
     */
    public InsertCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        brandTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        engineTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        powerTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        doorsTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        seatsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Set the Brand");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));
        getContentPane().add(brandTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 43, 66, -1));
        getContentPane().add(modelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 121, 70, -1));

        jLabel2.setText("Set Model");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 89, 66, -1));
        getContentPane().add(engineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 191, 70, -1));

        jLabel3.setText("Set the Engine");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 159, -1, -1));

        jLabel4.setText("Set the Power");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 222, 70, -1));
        getContentPane().add(powerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 254, 70, -1));
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 51, 70, -1));

        jLabel5.setText("Set the Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, 99, -1));
        getContentPane().add(doorsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 121, 70, -1));

        jLabel6.setText("Set number of Doors");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 89, -1, -1));
        getContentPane().add(seatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 191, 70, -1));

        jLabel7.setText("Set number of Seats");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 159, 99, -1));
        getContentPane().add(colourTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 254, 70, -1));

        jLabel8.setText("Set the Colour");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 222, 99, -1));

        jButton1.setText("Entry");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2016-Ford-Mustang-GT-burnout-red-tire-smoke2.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 300, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brandTextField;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JTextField doorsTextField;
    private javax.swing.JTextField engineTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField powerTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField seatsTextField;
    // End of variables declaration//GEN-END:variables
}
